---
- name: skiping_certs 
  hosts: ios_devices 
  gather_facts: false
  connection: local
  ignore_errors: yes
  tasks:
  - name: skiping cert configuration
    include_role:
      name: skiping_cert_cisco
