---
- name: Rotina de Backup
  hosts: ios_devices 
  gather_facts: true
  connection: local
 
  tasks:
  
  - name: Show Running config 
    ios_command:
      commands:
        - show running 
    register: config 

  - name: Gravando Arquivo 
    copy:
      content: "{{config.stdout[0]}}"
      dest: "/etc/ansible/Claro/backups/show_running_{{inventory_hostname}}.txt" 
