---
- name: Inventario
  hosts: ios_devices 
  gather_facts: true
  connection: local
 
  tasks:
  
  - name: Rotina inventario
    ios_command:
      commands:
        - show inventory 
    register: config 

  - name: Gravando Arquivo 
    copy:
      content: "{{config.stdout[0]}}"
      dest: "/tmp/show_platform_{{inventory_hostname}}.txt" 
